version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: intensive_bot
      POSTGRES_USER: intensive_bot
      POSTGRES_PASSWORD: intensive_bot
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
